version: '3'

services:
  screen:
    image: screen
    init: true
    ports:
      - 8800:8800
    volumes:
      - ./src:/app
# OPTIONAL FOR MULTI SECREENS with Traefik
#    networks: 
#      - proxy
    restart: unless-stopped

#OPTIONAL FOR MULTI SCREENS with Traefik
#networks:
#   proxy:
#     external: true

